Add release step

diff --git a/.github/workflows/releaser.yaml b/.github/workflows/releaser.yaml
--- a/.github/workflows/releaser.yaml
+++ b/.github/workflows/releaser.yaml
@@ -6,6 +6,7 @@ env:
   IMAGE_WIDTH: 2000
   IMAGE_HEIGHT: 2000
   OUTPUT_DIR: release
+  REVISION: ${{ steps.revision.outputs.revision }}
 on:
   workflow_dispatch:
 jobs:
@@ -18,10 +19,18 @@ jobs:
           submodules: recursive
 
       - name: Extract revision
+        id: revision
         run: |
           REVISION=$(jq -r '.text_variables.REVISION' "$PROJECT_FILE")
           if [ -z "$REVISION" ] || [ "$REVISION" = "null" ]; then
             echo "ERROR: REVISION field is missing"
+            exit 1
+          fi
+
+      - name: Validate revision number
+        run: |
+          if gh release view "$REVISION" >/dev/null 2>&1; then
+            echo "ERROR: Release $REVISION already exists"
             exit 1
           fi
 
@@ -41,7 +50,7 @@ jobs:
       - name: Generate PCB PDF
         run: |
           kicad-cli pcb export pdf "$PCB_FILE" \
-          --output "$OUTPUT_DIR" \
+          --output "$OUTPUT_DIR"/board.pdf \
           --mode-multipage \
           --include-border-title \
           --sketch-pads-on-fab-layers \
@@ -109,3 +118,9 @@ jobs:
           --height 2000 \
           --zoom 0.9 \
           --rotate 315,180,135
+
+      - name: Create GitHub release
+        run: |
+          zip release.zip "$OUTPUT_DIR"
+          gh release create "$REVISION" release.zip \
+          --title "$REVISION"
